### ISSUE TITLE
Create a DatasourceModule providing access to a JDBC Datasource

### ISSUE THREAD

**Issue by mmihic** [square/misk#175]
We should provide a ``DatasourceModule`` for connecting to a JDBC database instance. This should _not_ be tied in to Hibernate or other framework; it should just bind a raw JDBC ``Datasource``, optionally qualified by an annotation specified by the installer. Services that want to use higher level frameworks can install other modules that use the bound datasource to initialize those frameworks. The ``DatasourceModule`` should use the Hikari connection pool and be opinionated on which configuration options are allowed (fixed pool size, pool check timeout, etc). It should also install appropriate readiness checks to prevent a service from reporting itself as ready until after connectivity to the database has been confirmed, and expose appropriate database metrics.

Example install:

```kotlin
fun main(args: Array<String>) {
   val serviceConfig = MiskConfig.load<ExemplarConfig>("exemplar",
       Environment.fromEnvironmentVariable())
   MiskApplication(
       listOf(
          ConfigModule.create("exemplar", serviceConfig),
          TracingModule(serviceConfig.tracing),

          // Installs datasource support, binding it to an unqualified Datasource
          DatasourceModule(“exemplar”),
      
          // Installs a second datasource for read-replica access, binding it to 
          // a Datasource qualified by the  @ReadReplica binding annotation
          DatasourceModule("exemplar-readonly", annotatedBy=ReadReplica::class))
   ).run(args)
}

class MyAction : WebAction {
  @Inject lateinit var primaryDatasource: DataSource
  @Inject @ReadReplica lateinit var readOnlyDatasource: DataSource
}
```

Example configuration:

```yaml
default_db_settings: &default_db_settings
    type: mysql
    username: exemplar
    password: 
    connection_properties: zeroDateTimeBehavior=convertToNull
    fixed_pool_size: 10
    pool_check_timeout: 30ms
    max_conn_lifetime: 1m

datasources:  
  exemplar:
    <<: *default_db_settings
    host: exemplar.cluster-cmxb34unfd.us-west-2.rds.amazonaws.com 

  exemplar-readonly:
    <<: *default_db_settings
    host: exemplar.cluster-cmxb34unfd-ro.us-west-2.rds.amazonaws.com 
```

Theoretical example also using Hibernate:

```kotlin
fun main(args: Array<String>) {
   val serviceConfig = MiskConfig.load<ExemplarConfig>("exemplar",
       Environment.fromEnvironmentVariable())
   MiskApplication(
       listOf(
          ConfigModule.create("exemplar", serviceConfig),
          TracingModule(serviceConfig.tracing),

          // Installs datasource support, binding it to a Datasource qualified by 
          // a @Primary binding annotation
          DatasourceModule(“exemplar”, annotatedBy = Primary::class),

          // Installs a second datasource for read-only access, binding it to a Datasource
          // qualified by a @ReadReplica binding annotation
          DatasourceModule("exemplar-readonly", annotatedBy = ReadReplica::class),

          // Installs hibernate support, telling it to use the Datasource with the @Primary
          // binding annotation for writable transactions and the datasource annotated with the
          // @ReadReplica binding annotation 
          HibernateModule(
               datasourceAnnotatedBy = Primary::class,
               readOnlyDatasourceAnnotatedBy = ReadReplica::class)
   ).run(args)
}
```
